# Generated by Django 3.2.14 on 2022-07-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('productgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.productgroup')),
            ],
        ),
    ]
