# Generated by Django 3.2.14 on 2022-07-25 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
