# Generated by Django 3.2.14 on 2022-07-26 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_auto_20220725_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
