# Generated by Django 3.2.14 on 2022-07-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_product_production_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='production_date',
            new_name='paking_date',
        ),
    ]
