# Generated by Django 3.2.14 on 2022-07-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_rename_production_date_product_paking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='paking_date',
            field=models.DateField(),
        ),
    ]
