# Generated by Django 3.2.14 on 2022-07-26 06:00

from django.db import migrations, models
from datetime import *


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0006_remove_product_paking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paking_date',
            field=models.DateField(default=datetime.today),
            preserve_default=False,
        ),
    ]
