# Generated by Django 3.2.14 on 2022-07-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0009_auto_20220726_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='paking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
