# Generated by Django 3.2.14 on 2022-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0011_alter_product_paking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
