# Generated by Django 3.1.6 on 2022-08-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0013_auto_20220804_0728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('productgroup', 'variety')},
        ),
    ]
