# Generated by Django 3.1.6 on 2022-08-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0014_auto_20220804_0732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('price', 'quantity')},
        ),
    ]
